<?php include "header.phtml"; ?>
<h1>About this website</h1>
<p>This website is designed to use PHP, JavaScript and XHTML forms to create what is
	essentially a shop</p>
<h2>Disclaimer</h2>
<p>THIS IS NOT A REAL WEB SHOP; IT IS CREATED AS PART OF MY UNIVERSITY COURSEWORK.</p>
<p>Although information security has been attempted, because of this website's nature
	information may not be secure once entered so don't enter any personal details. This
	website is for educational purposes only.</p>
<h2>Declaration of Origonality</h2>
<p>This submission is my own work, except where clearly indicated. I understand that there are severe penalties for plagiarism and other unfair practice, which can lead to loss of marks or even the withholding of a degree. I have read the sections on unfair practice in the Students’ Examinations Handbook and the relevant sections of the current Student Handbook of the Department of Computer Science. I understand and agree to abide by the University’s regulations governing these issues.</p>
<?php include "footer.phtml"; ?>