<?php include "header.phtml"; ?>
<h1>Enter (fake) payment details</h1>
<p>To checkout, you need to input your details below.</p>
<p>This is your last chance to change your order.</p>
<form action="checkout.php" method="post">
	<label>Email:</label><br />
	<input type="text" size="30" name="emailAddress" /><br />
	<label>Card Number (16 numerical) digits: </label><br />
	<input type="text" size="30" name="cardNumber" /><br />
	<input type="submit" name="checkoutSubmit" value="Confirm (fake) purchase" />
</form>

<?php include "footer.phtml"; ?>