<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>webshop</title>
	<meta http-equiv="content-type" 
		content="text/html;charset=utf-8" />
	<link rel="stylesheet" type="text/css" href="template/style.css" />
</head>
<body>
	<div id="disclaimer">
		<p>THIS IS NOT A REAL WEB SHOP; IT IS CREATED AS PART OF MY UNIVERSITY COURSEWORK. PLEASE DO NOT ATTEMPT TO BUY ANYTHING FROM THIS SITE, NOR ENTER YOUR REAL CARD DETAILS.</p>
	</div>

	<div id="page">
		<div id="header">
			<div id="title">
				<h1>CSGames Online Store</h1>
			</div>
		</div>
		<div id="nav">
			<ul>
				<li><a href="index.php"> Home </a> </li>
				<li><a href="about.php"> About </a> </li>
				<li><a href="shop.php"> Shop </a> </li>
				<li><a href="basket.php"> Basket </a> </li>
			</ul>
		</div>
		<div id="bodyarea">
			<div id="loginForm">
					<?php if ($this->logged_in == False) : ?>
						<form action="login.php" method="post">
						<ul>
					        <li><input name="name" size="13" /></li>
					        <li><input type="submit" value="login" /></li>
					    </ul>
					    </form>
					<?php else : ?>
					    <ul>
						<li>Welcome <?=$this->user_name ?></li>
						<li><a href="logout.php">logout</a></li>
					    </ul>
					<?php endif; ?>
			</div>
