<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>webshop</title>
	<link rel="stylesheet" href="template/style.css" />
</head>
<body>
	<div id="disclaimer">
		<p>THIS IS NOT A REAL WEB SHOP; IT IS CREATED AS PART OF MY UNIVERSITY COURSEWORK. PLEASE DO NOT ATTEMPT TO BUY ANYTHING FROM THIS SITE, NOR ENTER YOUR REAL CARD DETAILS.</p>
	</div>

	<div id="page">
		<div id="header">
			<div id="title">
				<h1>CSGames Online Store</h1>
			</div>
		</div>
		<div id="nav">
			<ul>
				<li><a href="index.php"> Home </a> </li>
				<li><a href="about.php"> About </a> </li>
				<li><a href="#"> Writeup </a> </li>
				<li><a href="shop.php"> Shop </a> </li>
			</ul>
		</div>
		<div id="bodyarea">
			<div id="loginForm">
				<ul>
					<?php if ($this->logged_in == False) : ?>
						<form action="login.php" method="POST">
					        <li><input name="name" size="13" /></li>
					        <li><input type="submit" value="login" /></li>
					    </form>
					<?php else : ?>
						<li>Welcome <?=$this->user_name ?></li>
						<li><a href="logout.php">logout</a></li>
					<?php endif; ?>
				</ul>
			</div>
