<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="template/style.css" />
</head>
<body>
	<div id="disclaimer">
		<p>THIS IS NOT A REAL WEB SHOP; IT IS CREATED AS PART OF MY UNIVERSITY COURSEWORK. PLEASE DO NOT ATTEMPT TO BUY ANYTHING FROM THIS SITE, NOR ENTER YOUR REAL CARD DETAILS.</p>
	</div>

	<div id="page">
		<div id="header">
			<div id="title">
				<h1>CSGames Online Store</h1>
			</div>
		</div>
		<div id="nav">
			<ul>
				<li><a href="index.php"> Home </a> </li>
				<li><a href="about.php"> About </a> </li>
				<li><a href="#"> Writeup </a> </li>
			</ul>
		</div>
		<div id="bodyarea">

			<div id="loginForm">
			    <ul>
			        <li><input size="13" type="password" /></li>
			        <li><input type="submit" value="login" /></li>
			    </ul>
			</div>