<?php include $this->"header.phtml"; ?>
<h1>Welcome to my Online Shop</h1>
<p>To begin your shopping session please enter your 
name into the box on the top right corner of this page. 
When you have done this you will be able to browse the 
store and make any purchases you want.</p>
<p>To see the documentation, please use the writeup link
on the navigation bar above. The about page is NOT the 
documenation</p>
<p><b>This is not a real web shop</b>, if you want more
information take a look at the <a href="about.php">about page</a>. For the <a href="about.php">Declaration of origonality</a>, use the <a href="about.php">about link</a>. There is also a
<b><a href="about.php">disclaimer</a></b> associated with 
use of this website, so please take a look.</p>
<?php include $this->"footer.phtml"; ?>