<?php include "header.phtml"; ?>
<h1>This is the page title</h1>
<p>researched deployment from version control
found https://gist.github.com/1809044 (complicated)
http://net.tutsplus.com/tutorials/other/the-perfect-workflow-with-git-github-and-ssh/ (more simple)
Decided simply to work on central pushing to github.</p>
<p>esearched templating
found smarty
looked at using plain php</p>
<?php include "footer.phtml"; ?>